version: 2.0

jobs:
  build:
    working_directory: ~/mns
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          key: mns-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: mns-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      #- run: npm run e2e -- --protractor-config=e2e/protractor.conf.js

      - run:
          name: Compiles the app into an output directory named dist/
          command: npm run build
      - run:
          name: TODO@Idrice  See issue#104
          command: dir
      - run:
          name: Deploy the app into an output directory named docs for real app
          command: npm run deploy
